name: .NET CI and Docker Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore ./DevOps/DevOps.sln

    - name: Build
      run: dotnet build ./DevOps/DevOps.sln --no-restore

    - name: Run tests
      run: dotnet test ./DevOps/DevOps.sln --no-build --verbosity normal

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./DevOps
        file: ./DevOps/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/devops:latest

    - name: Log out from Docker Hub
      run: docker logout
